GOPATH=`pwd`

build:
	@echo "Building Alertstrap..."
	@GOPATH=${GOPATH} go build -o bin/alertstrap alertstrap.go
	@echo "Building Jiramanager..."
	@GOPATH=${GOPATH} go build -o bin/jiramanager jiramanager.go
